### ISSUE TITLE
Make Column label max_length longer than 50

### ISSUE THREAD

**Issue by oTree-org** [magopian/django-data-exports#9]
On a few occasions I have had the issue that some of my field names are longer than 50 chars. Or, I would like a label that is longer than 50 chars, since it's an attribute on an FK model (like "my_model.another_model.field_on_that_model"). Since the column itself can be 255 chars, I wonder if it would make sense to up the limit on the label to 255 as well.

**Comment by oTree-org** [comment]
Not high priority for me anymore. I removed my dependency on django-data-exports since I needed some custom functionality.

**Comment by magopian** [comment]
hi @wickens, I'm happy that you found a solution to your problem, even thought it's without data-exports ;)

I'm sorry I didn't have time to answer nor look into this request earlier, I hope to carve some time out for this, but no clue when.

Anyway, thanks for the report!
